import type { Night } from '../types';

export const SESSION_1_2026: Omit<Night, 'id'>[] = [
  { allStaffOnDuty: true,  typeId: 'closed',        label: '6/28 arrival' },
  { allStaffOnDuty: false, typeId: 'open',           label: '6/29' },
  { allStaffOnDuty: false, typeId: 'closedMeeting',  label: '6/30 staff meeting' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/1' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/2' },
  { allStaffOnDuty: false, typeId: 'closed',         label: '7/3' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/4 12:30am' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/5' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/6' },
  { allStaffOnDuty: false, typeId: 'closedMeeting',  label: '7/7 staff meeting' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/8' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/9' },
  { allStaffOnDuty: false, typeId: 'closed',         label: '7/10' },
  { allStaffOnDuty: false, typeId: 'closedMeeting',  label: '7/11 staff meeting' },
  { allStaffOnDuty: false, typeId: 'openHeavy',      label: '7/12 visitors day' },
  { allStaffOnDuty: false, typeId: 'closedMeeting',  label: '7/13 staff meeting' },
  { allStaffOnDuty: false, typeId: 'closed',         label: '7/14' },
  { allStaffOnDuty: false, typeId: 'closed',         label: '7/15' },
  { allStaffOnDuty: false, typeId: 'openHeavy',      label: '7/16 night after MP' },
  { allStaffOnDuty: false, typeId: 'closed',         label: '7/17' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/18 12:30am' },
  { allStaffOnDuty: false, typeId: 'closed',         label: '7/19' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/20' },
  { allStaffOnDuty: false, typeId: 'open',           label: '7/21' },
  { allStaffOnDuty: false, typeId: 'closedMeeting',  label: '7/22 staff meeting' },
  { allStaffOnDuty: false, typeId: 'closed',         label: '7/23' },
  { allStaffOnDuty: true,  typeId: 'closed',         label: '7/24 last day session 1' },
];
